### PR TITLE
Contrib cleanup

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by mstg** [comment]
Could you also pull in the changes related to modulemd/module component? Otherwise looks good

**Comment by dirkmueller** [comment]
@mstg: I can do that, wanted to give you the honor.. will do 1-2 hours

**Comment by mstg** [comment]
Thank you and no rush. Also thanks for the consideration. It's OK though, we're a team and it would be cleaner to pull in all the new changes in this PR. Let me know when you want me to take a look

**Comment by gmkurtzer** [comment]
Heh, I said the same thing to Mustafa. ;-)

Thanks team!

**Comment by dirkmueller** [comment]
All the changes are in and ready for review.

**Review by mstg — APPROVED** [review]

**Comment by mstg** [comment]
Awesome, thank you @dirkmueller

**Comment by gmkurtzer** [comment]
This is fantastic, thank you!

**Pull request merged**
